communitiesuk/prsdb-webapp

src/main/resources/application-local.yml
Updates hibernate config when running locally to avoid crash from incorrectly re-seeding the database when hot-reloading
=> PRSD-NONE: Prevents error on hot reload from re-seeding data

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ExampleEmailSendingController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/EmailTemplateModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/ExampleEmail.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/EmailNotificationService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/NotifyEmailNotificationService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/EmailTemplateModelsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/notify/NotifyEmailTemplateTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/NotifyEmailNotificationServiceTests.kt
Moving the email template view models to the models folder as discussed.
=> PRSD-364: Move email template models

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ExampleEmailSendingController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/exceptions/PersistentEmailSendException.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/exceptions/TransientEmailSentException.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/local/services/EmailNotificationStubService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/EmailTemplateModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/ExampleEmail.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/EmailNotificationService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/NotifyEmailNotificationService.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/EmailTemplateModelsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/notify/NotifyEmailTemplateTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/NotifyEmailNotificationServiceTests.kt
Added a stubbed email sending service. I've annotated with the profile "!use-notify" even though "use-notify" doesn't currently exist as it lets you easily connect to notify for real during local development by adding that profile to your build configuration. I've also created some email addressed to simulate the two exception types that can be thrown by the notify email service.
=> PRSD-364: Stub calls to notify for local

src/test/kotlin/uk/gov/communities/prsdb/webapp/notify/NotifyEmailTemplateTests.kt
Not sure if this is necessary or not (or if this file is the right place) but I wanted to include an explanation for if someone noticed that a chunk of tests are disabled when they run them locally. 
Also, we should (before PRSD-404) add the appropriate environment variable to the test runner so that the PR tests fail if someone hasn't set this up correctly.
Let me know what you think.
=> PRSD-364: Add block comment to notify tests

src/main/resources/application-local.yml
Uses fake API key for stubbed OS Places calls
=> PRSD-362: Run OS Places stub without having API key

src/test/kotlin/uk/gov/communities/prsdb/webapp/clients/OSPlacesClientTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/ManageLAUsersTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityInvitationServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/NotifyEmailNotificationServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/OSPlacesAddressLookupServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/RegistrationNumberServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/UserRolesServiceTests.kt
Added `mockito.kotlin` in a previous PR, this just removes the very ugly `` `when` `` from the tests and replaces it with the much easier to read `whenever`.
=> PRSD-NONE: Replace  with whenever

src/main/kotlin/uk/gov/communities/prsdb/webapp/config/CustomSecurityConfig.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SignOutController.kt, src/main/resources/data-local.sql, src/main/resources/templates/exampleConfirmSignOut.html, src/main/resources/templates/fragments/header/authenticatedHeader.html
- Creates a `/confirm-sign-out` endpoint with a submit button that logs the user out of OneLogin
- Points the OneLogin header's 'Sign Out' link to `/confirm-sign-out`
- Sets the post OneLogin logout redirect URL to `/signout`
Confirm Sign Out Page:
- Integration tests are required to check that the logout functionality works, but the configuration required for integration tests has not been done yet
=> PRSD-452: One Login Logout

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/LocalAuthority.kt, src/main/resources/messages.properties, src/main/resources/templates/fragments/confirmationPageBanner.html, src/main/resources/templates/fragments/primaryButtonLink.html, src/main/resources/templates/fragments/secondaryButtonLink.html, src/main/resources/templates/inviteLAUserSuccess.html, src/main/resources/templates/manageLAUsers.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ControllerTest.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/IntegrationTest.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/InvitationUrlTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/InviteLaUsersTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/ManageLAUsersTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/components/BaseComponent.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/components/ConfirmationPageBanner.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/components/TextInput.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/BasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/InviteNewLaUserPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/InviteNewLaUserSuccessPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/Navigator.kt
This PR finishes off the last bits of PRSD-404, namely:
- After inviting a new user, we show a properly styled confirmation page
- The manage LA users page has a button to invite new users, which is now wired up to this page
- There are some controller tests for the invite journey
- There are some e2e tests for the invite journey
Note that as part of the above I've introduced:
- Primary and secondary buttons that look like links
- The beginnings of a Page Object style framework for e2e tests; I'm not that familiar with Playwright, so we might want to evolve a bit as we learn what works well, but here's a starting point
=> PRSD-404: add success page, link from manage users page, add Page Object style e2e tests

src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/ManageLAUsersTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/components/Pagination.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/components/Table.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/BasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/InviteNewLaUserPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/ManageLaUsersPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/Navigator.kt
The ManageLAUsersTests were written as the same time as I was introducing the page objects pattern for integration tests. I've rewritten them in that style, here.
=> PRSD-NONE: ManageLAUsersTests uses page objects

src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/InviteLaUsersTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/InviteNewLaUserSuccessPage.kt
Andrea has requested that we use the word "invite" instead of "invitation" in user facing copy, on the basis that it's less formal and helps with reading comprehension.
=> PRSD-NONE: Use 'invite' instead of 'invitation' in user facing copy

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataService.kt, src/main/resources/messages.properties, src/main/resources/templates/deleteLAUser.html, src/main/resources/templates/deleteLAUserSuccess.html, src/main/resources/templates/editLAUserAccess.html, src/main/resources/templates/fragments/warningText.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/EditLAUserTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/ConfirmDeleteLaUserPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/DeleteLaUserSuccessPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/EditLaUserPage.kt
This PR allows LA admins to delete other users in their LA. In particular:
- Adds an "are you sure" style screen, and wires the delete button the edit page up to that
- Handles the delete POST from that page, deleting the user
- Redirects to a confirmation screen
- Adds a [Warning Text](https://design-system.service.gov.uk/components/warning-text/) fragment
=> PRSD-407: Delete LA users (via confirm screen)

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/LocalAuthorityUser.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataService.kt, src/main/resources/templates/manageLAUsers.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/InvitationUrlTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/ManageLAUsersTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageobjects/pages/ManageLaUsersPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/mockObjects/MockLocalAuthorityData.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataServiceTests.kt
As discussed on Slack, we think it makes sense to prevent LA admin users from editing their own accounts (so they can't downgrade themselves to basic access, and leave the LA with no admins) or removing themselves from their LA. This PR achieves that by:
- Removing the "Change" link the manage users table for the current user
- Throwing a 403 Forbidden if the user tries to access any pages / make any posts to edit themselves
- Throwing a 403 Forbidden if the user tries to access nay pages / make any posts to remove themselves
=> PRSD-406 / PRSD-407: Disallow LA admins editing or removing themselves

src/main/resources/templates/fragments/forms/backLink.html
This is a tiny change to:
1. Enclose the "Back" link in `<nav>`, which I think makes sense
2. Use the browser back functionality via JS, if JS is available
I've tested this works happily in Chrome both with JS enabled (back/forward works as you'd expect) and disabled (clicking the back link adds a new item to history).
=> PRSD-NONE: Back link is in nav, uses JS if available

build.gradle.kts
Upgrade spring book to version 3.3.5 to mitigate this vulnerability
https://spring.io/security/cve-2024-38819
=> PRSD-NONE: upgrade spring boot to version 3.3.5

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/SelectAddressPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/local/api/controllers/OSPlacesAPIStubController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/AddressDataModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/AddressDataService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/OSPlacesAddressLookupService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/AddressDataServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/OSPlacesAddressLookupServiceTests.kt
- Matches `AddressDataModel` to the MVP Address data model
- Creates and tests `AddressDataService`, which handles address caching
- Caches looked-up addresses in after retrieving them in `SelectAddressPage`
- Overrides `isSatisfied` on landlord registration select address steps to check that the submitted value matches a cached address
=> PRSD-562: Cache Looked-up Addresses

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/enums/LicensingType.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/RegisterPropertyStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/formModels/LicensingTypeFormModel.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/licensingTypeForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyRegistrationJourneyPages/LicensingTypeFormPagePropertyRegistration.kt
Added the lincensing type page and integration tests. I'm not sure if I've added this in exactly the correct place in the journey but updating the `nextAction`s later once the all the pages exist should be relatively easy (and means we're not blocked on previous steps now!)
=> Prsd 578 select licensing type

src/main/resources/templates/examples/exampleLandlordSearch.html, src/main/resources/templates/forms/lookupAddressForm.html, src/main/resources/templates/forms/manualAddressForm.html, src/main/resources/templates/forms/nameForm.html, src/main/resources/templates/forms/selectiveLicenceForm.html, src/main/resources/templates/fragments/conditional/customPropertyTypeInput.html, src/main/resources/templates/fragments/forms/basicTextInput.html, src/main/resources/templates/fragments/forms/fixedWidthTextInput.html, src/main/resources/templates/fragments/forms/innerTextInput.html, src/main/resources/templates/fragments/forms/numericalInput.html
Two main changes here:
* Make separate fragments for a fluid width and fixed width text input to avoid passing lots of nulls.
* Assert that a valid width is being passed as the width parameter to protect against future mistakes.
I dont want to mess up Jasmin's otherwise good PR with this set of changes while she's away but since it's related I'm setting this as a draft merging into that PR.
@Travis-Softwire - if you like this approach I can do the same for the numerical input.
=> PRSD-491: Check field widths in templates

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/RegisterPropertyStepId.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/propertyRegistrationCheckAnswersForm.html, src/main/resources/templates/fragments/tabs/tabs.html, src/main/resources/templates/fragments/tabs/tabsHeadingList.html, src/main/resources/templates/fragments/tabs/tabsListItem.html, src/main/resources/templates/fragments/tabs/tabsPanel.html
Create the template for the register-property check answers page, with placeholder text for the additional landlords and interested parties tabs. The rest of this ticket will involve modifying the "propertyDetails" `List` returned from the `Journey` to have the correct list of details in all circumstances and ensuring the journey flows correctly. This ticket is explictly just for the UI.
=> PRSD-495: Add property registration check answers template

src/main/resources/templates/forms/licenceNumberForm.html, src/main/resources/templates/fragments/forms/numericalInput.html
Two minor changes:
* Use a fixed width input for licence number input to better match the designs
* Fix an issue with the numerical input that was causing them to ignore the input value
The width I've selected on the licensing page is a little wider than [the designs](https://www.figma.com/design/ka4URNl45NiQO0LoY8XNe4/MHCLG---Private-Rented-Sector-Database?node-id=8457-364445&t=ly8OKk6KyQV37biw-0) but the designs are between 10 and 20 width and I thought this looked better that the 10 width option (see bottom)
Twenty width:
Ten width:
=> PRSD-579: Fix fixed input widths

src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/AddressDataModel.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/AddressDataModelTests.kt
Makes `AddressDataModel.manualAddressDataToSingleLineAddress` tolerate blank manual address fields
=> PRSD-641: Tolerate blank manual address fields

src/main/resources/templates/fragments/forms/backLink.html
Reverted commit `8c4ea3cff6af272b8c6de05b94fc24cbb82618c7` which brought in the bug to the back link by using `javascript:history.back()`
=> bug/PRSD-543 fix multi-page forms back link

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/resources/messages.properties, src/main/resources/templates/fragments/tables/table.html, src/main/resources/templates/manageLAUsers.html, src/main/resources/templates/registerPropertyConfirmation.html, src/main/resources/templates/searchLandlord.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/SearchRegisterTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/SearchLandlordRegisterPage.kt
Overarching changes:
- Adds optional caption to `table.html`
Features:
- Updates search landlord page to show error when no results are found
- Creates placeholder property search endpoint
Tests:
- Updates integration tests for landlord search page
Screenshot:
=> PRSD-650: Landlord Search - No Results

src/main/resources/data-local.sql, src/main/resources/templates/landlordDetailsView.html
Now that the Registered property tab in the Landlord Record ("/landlord-details") has been merged in addresses in local data will need to have custodian codes to be able to populate the `RegisteredPropertyDataModel`. This PR adds custodian codes to the addresses in `data-local.sql`
=> chore/PRSD-NONE: add custodian codes to addresses in local-data

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/database/repository/LandlordRepository.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/RegistrationNumberDataModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/RegistrationNumberDataModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/LandlordViewModelTest.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordServiceTests.kt
- Creates `LandlordRepository` methods for searching by a LRN or query with an optional LA filter
- Updates `LandlordService.searchForLandlords()` to use these repository methods
- Updates the affected tests
=> PRSD-651: Landlord Search LA Filter Service

src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/LocalAuthorityUserOrInvitation.kt
I noticed that when starting the Spring app it logs the following warnings:
> HHH000038: Composite-id class does not override equals(): uk.gov.communities.prsdb.webapp.database.entity.LocalAuthorityUserOrInvitation$CompositeKey
HHH000039: Composite-id class does not override hashCode(): uk.gov.communities.prsdb.webapp.database.entity.LocalAuthorityUserOrInvitation$CompositeKey
Turns out the JPA spec requires that ID classes implement equals and hashCode, so I've turned CompositeKey into a data class to generate those methods. The spec also requires that ID classes are Serializable - I'm not really sure why, and we weren't getting warnings about that, but I've also made it Serializable just in case!
=> Fix Hibernate startup warnings about LocalAuthorityUserOrInvitation#CompositeKey

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/resources/emails/PropertyRegistrationConfirmation.md, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyRegistrationJourneyTests.kt
Fixes a typo, also changes the link so that it hopefully renders correctly in emails
(The www. version was showing next to the text for Kiran, rather than as a hyperlink)
=> PRSD-596: fix "Sign in..." link

src/main/resources/templates/fragments/taskList/taskListItem.html
The names of "Cannot start yet" tasks should not display as links.
=> PRSD-600: Don't diplay absent links

src/test/kotlin/uk/gov/communities/prsdb/webapp/mockObjects/MockLandlordData.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/LandlordViewModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordServiceTests.kt
- This avoids 'unnecessary stubbings' errors
=> PRSD-NONE: Uses reflection to set mock landlord createdDate

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/PaginationConstants.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/database/repository/PropertyOwnershipRepository.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyOwnershipService.kt, src/main/resources/templates/searchProperty.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/SearchRegisterTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/FilterPanel.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/Pagination.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/Table.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/SearchRegisterBasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyOwnershipServiceTests.kt, src/test/resources/data-search.sql
Features:
- Updates `PropertyOwnershipService.searchForProperties` to return a (requested) page
- Adds pagination to property search page
Tests:
- Updates affected `PropertyOwnershipService.searchForProperties` tests
- Tests pagination in 
- PropertyOwnershipService.searchProperties
- Property search endpoint
- Property search page
Screenshot:
=> PRSD-661: Property Search Pagination

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/tasks/MultiTaskTransaction.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/tasks/RegisterPropertyMultiTaskTransaction.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/TaskSectionViewModel.kt, src/main/resources/templates/fragments/taskList/sectionTaskList.html, src/main/resources/templates/registerPropertyTaskList.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/MultiTaskTransactionTests.kt
Final PR for PRSD-600: Adds numbering to the titles and makes the template use a list of fragments to generate the sections. I rename some terminology based on other ongoing discussion and update the tests to match the new View Models.
=> PRSD-600: Create transaction section fragment and use section list

src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/searchModels/SearchRequestModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/filterPanelModels/FilterPanelViewModel.kt, src/main/resources/messages.properties, src/main/resources/templates/fragments/filterPanel.html, src/main/resources/templates/fragments/searchBar.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/SearchRegisterTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/BaseComponent.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/FilterPanel.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/BasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/SearchRegisterBasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/ConfirmationPageLandlordRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyRegistrationJourneyPages/ConfirmationPagePropertyRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/SearchRequestModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/FilterPanelViewModelTests.kt
Features:
- Hides filter category heading if none of its options are selected
- Hides clear filters link and shows message when no filters are selected
- Persists selected filters across searches
Tests:
- Updates search page integration tests
- Creates `SearchRequestModelTests`
- Creates `FilterPanelViewModelTests`
Screenshot:
=> PRSD-651: Update Selected Filter View

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/enums/LicensingType.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/RegisteredPropertyViewModel.kt, src/main/resources/templates/landlordDetailsView.html, src/main/resources/templates/localAuthorityLandlordDetailsView.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/RegisteredPropertyViewModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyOwnershipServiceTests.kt
On the Landlord Record page in the property details tab - changed some of the displayed names for `LicencingType`, by using the `MessageKeyConverter` in `RegisteredPropertyViewModel` so that the names are unified across all screens.
Changes:
HMO licence -> HMO mandatory licence
Additional licence -> HMO additional licence
Not Licenced -> None
=> feat/PRSD-785 Align licensing terminology across screens

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/URIQueryBuilder.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/searchModels/LandlordSearchRequestModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/searchModels/PropertySearchRequestModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/searchModels/SearchRequestModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/filterPanelModels/FilterPanelViewModel.kt, src/main/resources/templates/fragments/filterPanel.html, src/main/resources/templates/fragments/searchBar.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/URIQueryBuilderTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/SearchRequestModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/FilterPanelViewModelTests.kt
- Manually determines the state of each filter checkbox rather than letting Spring do it. This is done to avoid the hidden values [Spring+Thymeleaf](https://www.thymeleaf.org/doc/tutorials/3.1/thymeleafspring.html#checkbox-fields) adds to checkboxes.
- Makes `SearchRequestModel` filter properties nullable so filters only appear in URLs if they're active.
=> PRSD-663: Manually Bind Filter Request to View

src/main/kotlin/uk/gov/communities/prsdb/webapp/database/repository/OneLoginUserRepository.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/OneLoginUserService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/OneLoginUserServiceTests.kt
- Creates and tests `OneLoginUserService.findOrCreate1LUser`
- Updates `LocalAuthorityDataService.registerNewUser` (and its tests) to save the user's 1L details
=> PRSD-878: LA Registration - Save 1L User

src/main/kotlin/uk/gov/communities/prsdb/webapp/database/repository/OneLoginUserRepository.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/OneLoginUserService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LandlordServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/OneLoginUserServiceTests.kt
- Updates `LandlordService.createLandlord` (and its tests) to save the user's 1L details
=> PRSD-879: Landlord Registration - Save 1L User

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LaUserRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/PropertyRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationServiceTests.kt
- Makes LA and property registration journeys interact with session via `LocalAuthorityDataService` and `PropertyRegistrationService` respectively
- Updates the affected tests
=> PRSD-648: Interact with Session via Services

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/SessionAttributes.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LaUserRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataService.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/PropertyRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LaUserRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/laUserRegistrationJourneyPages/ConfirmationPageLaUserRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityDataServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationServiceTests.kt
- Creates LA user in the `handleSubmitAndRedirect()` of the check answers step instead of the confirmation endpoint
- Adds ID of created LA user to session
- Uses cached ID to retrieve LA for confirmation page
- Updates affected tests
=> PRSD-648: Creates LA User in POST Request

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/LocalAuthorityUserDataModel.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/EditLAUserTests.kt
Removes a couple of stray todos from the codebase
=> PRSD-NONE: Remove completed todos for prsd-405 and prsd-659

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/ReadMe.md
This honestly ended up a little longer than I was expecting, but I think I've spent enough time on it and it covers pretty much everything.
I've based it on Isobel's branch so it will be true after than merges in! (E.g. the update journey being a separate class.
For the main function names on Journey I've suggested two titles for them. One is what they currently are and the other is what will make this documentation make more sense and therefore what I'm suggesting we refactor them too when it won't cause conflicts! I'll comment there and we should resolve  that and update the documentation to match the decision before merging in!
=> PRSD-NONE: Add ReadMe documentation for the journey framework

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/ExternalLinks.kt
The original link contains a uuid (this was a link from a ticket), but clicking on it redirects you to a page without a uuid.
It feels a bit cleaner to just use the link without the uuid!
=> PRSD-670: Replace link to external content

src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/PropertyOwnership.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/UpdatePropertyDetailsStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyDataExtensions/PropertyDetailsUpdateJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/updateModels/PropertyOwnershipUpdateModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsViewModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyOwnershipService.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyDataExtensions/PropertyDetailsUpdateJourneyDataExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyDetailsUpdateJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/NumberOfHouseholdsFormBasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/PropertyDetailsBasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyDetailsUpdateJourneyPages/NumberOfHouseholdsFormPagePropertyDetailsUpdate.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyRegistrationJourneyPages/NumberOfHouseholdsFormPagePropertyRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsViewModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyOwnershipServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
- Adds number of households to `PropertyOwnershipUpdateModel` and `PropertyOwnershipService.updatePropertyOwnership`
- Creates `PropertyDetailsUpdateJourneyDataExtensions.getNumberOfHouseholdsUpdateIfPresent()`
- Adds `NumberOfHouseholds` step to `PropertyDetailsUpdateJourney`
- Updates tests for `PropertyOwnershipService.updatePropertyOwnership`
- Adds tests for `PropertyDetailsUpdateJourneyDataExtensions.getNumberOfHouseholdsUpdateIfPresent()`
- Updates `PropertyDetailsUpdateJourneyTests` to include `NumberOfHouseholds` step
- Update details page
- Update number of households page
=> PRSD-800: Update Property - Number of Households

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDeregistrationJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/deregistrationReasonForm.html
Adds hint text to the property deregistration reason page
=> PRSD-697: Add hint text to property deregistration reason page

src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/PropertyOwnership.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/UpdatePropertyDetailsStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyDataExtensions/PropertyDetailsUpdateJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsViewModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/RegisteredPropertyViewModel.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyDataExtensions/PropertyDetailsUpdateJourneyDataExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyDetailsUpdateJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/OccupancyFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/PropertyDetailsBasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyDetailsUpdateJourneyPages/OccupancyFormPagePropertyDetailsUpdate.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyRegistrationJourneyPages/OccupancyFormPagePropertyRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsViewModelTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
- Adds `PropertyDetailsUpdateJourneyDataExtensions` methods for retrieving the original and updated occupation statuses
- Updates `PropertyDetailsUpdateJourneyDataExtensions` households and people number retrieval methods to return 0 if the property's occupation status has been updated to vacant
- Updates `PropertyDetailsUpdateJourney`
- Adds occupation step 
- Makes the number of people step follow the number of households one
- Updates the pages of the number of people and households steps to determine their `fieldSetHeading` via the original occupation status and their `backUrl` via the updated one.
- Adds tests for the new/updated `PropertyDetailsUpdateJourneyDataExtensions` methods
- Adds integration tests for new `PropertyDetailsUpdateJourney` functionality
- Update details page
- …
=> PRSD-799: Update Property - Occupation Status

adrs/0010-address-lookups.md, adrs/0026-address-lookups-revisited.md
Adds an ADR that revisits address lookups (superseding the original one), to address the issue of address data becoming stale after we save it from OS Places API.
=> PRSD-929: Address Lookups Revisited ADR-0026

src/main/resources/data-integration.sql, src/main/resources/data-test.sql
Copies the seed data from `data-integration.sql` with a couple of fixes. Specifically:
* UPRN 1 is a real UPRN, so changed the two used to 2 and 3 which are not currently in use.
* The single property ownership referenced `registration_number` 6, which does not exist. Updated to be 2 which does.
I've applied these fixes to the integration seed data as well.
=> PRSD-968: Copy integration seed data with fixes

.github/workflows/reset-database-integration.yml, .github/workflows/reset-database-test.yml, .github/workflows/reset-database.yml
- Cleans integration DB
- Checks out `main`
- Starts SSM port-forwarding session
- Retrieves integration DB parameters/secrets from SSM/Secrets manager and adds them to the environment
- Runs `flywayClean`
- Terminates the SSM session
- Restarts ECS
=> PRSD-1020: Github Action for manually resetting the integration DB

src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordDeregistrationJourneyTests.kt
Update the heading on the reason page of landlord deregistration
=> PRSD-891: Update reason page heading

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDeregistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDeregistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/UpdateLandlordDetailsJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordDeregistrationAreYouSurePage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/SelectAddressPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/UpdateLandlordDetailsJourneyDataHelper.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/JourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/LandlordDeregistrationJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyDeregistrationJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyDetailsUpdateJourneyExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/UpdateJourneyDataExtensions.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/LandlordRegistrationJourneyDataHelperTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/PropertyRegistrationJourneyDataHelperTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/JourneyDataExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyDetailsUpdateJourneyExtensionsTests.kt
Off the back of #315, this is a small refactoring to:
* rename the `journeyDataExtensions` package to `journeyExtensions`
* rename `PropertyDetailsUpdateJourneyDataExtensions` to `PropertyDetailsUpdateJourneyExtensions`
* move `getLicenceNumberStepIdAndFormModel` from `PropertyDetailsUpdateJourney` to `PropertyDetailsUpdateJourneyExtensions`
Note I haven't renamed any of the other `BlahJourneyDataExtensions` classes. I could do if people prefer, but I figured it might be easier / less conflict-y to do that as and when we introduce non-JourneyData extension methods into them.
=> PRSD-NONE: Rename journeyDataExtensions to journeyExtensions

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/templates/forms/gasSafetyOutdatedForm.html
PRSD-953
Makes EICR task reachable from Gas Safety Outdated step
- Updates gas safety outdated template button to send a POST request
- Updates gas safety outdated step to redirect to task list and make first step of EICR task reachable upon completion
N/A
- This feature will be tested when the EICR task's first step is implemented (PRSD-954)
=> PRSD-953: Makes EICR task reachable from Gas Safety Outdated step

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/GasSafetyFormModel.kt, src/main/resources/templates/forms/certificateForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
PRSD-954
Turns `gasSafetyForm` into a generic form that can be used for other certificate types
- Renames `gasSafetyForm` to `certificateForm` and corresponding form property `hasGasSafetyCert` to `hasCert`
N/A
=> PRSD-954: Turns gasSafetyForm into Generic certificateForm

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/InfrastructureValues.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/examples/ExampleFileUploadController.kt
PRSD-1001
Ensure that the urls for file uploads come from a source with a comment explaining how they interact with the WAF.
Created a constants file for InfrastructureConstants, which is then used to construct the example file upload URLs in the hope that future file upload endpoints will copy it.
=> PRSD-1001: Put file-upload into constants

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/CustomErrorController.kt, src/main/resources/messages.properties, src/main/resources/templates/error/fileTooLarge.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/ErrorPageTests.kt
PRSD-1003
Adds a 'file-too-large' error page we can redirect to from the WAF for very large requests.
Adds a 'file-too-large' error page we can redirect to from the WAF for very large requests.
Non final design - asked for copy from the designers, but updating the template should be easy.
=> PRSD-1003: Initial file-too-large page

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/uploadCertificateConfirmationForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/UploadConfirmationFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyUploadConfirmationPagePropertyCompliance.kt
PRSD-1098
Adds gas safety upload confirmation step to property compliance journey
- Creates template for gas safety upload confirmation page
- Adds gas safety upload confirmation step to property compliance journey
N/A
=> PRSD-1098: Property Compliance - Gas Safety Upload Confirmation Page

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/PropertyComplianceStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyExtensions.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrIssueDatePagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
PRSD-955
Adds EICR issue date step to property compliance journey
- Creates extension method for determining if the EICR is oudated
- Adds EICR issue date step to property compliance journey
N/A
=> PRSD-955: Property Compliance - EICR Issue Date

src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyDataExtensions.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/PropertyComplianceJourneyHelperTests.kt
PRSD-956
Removes redundant certificate file name helper method
- Removes redundant certificate file name helper method from property compliance journey extensions as the same method exists in property compliance journey helpers
N/A
=> PRSD-956: Removes redundant certificate file name helper

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/PropertyDetailsUpdateJourneyFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsViewModel.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/ownershipTypeForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyDetailsUpdateJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsViewModelTests.kt
PRSD-1107
Implements updating property ownership type without an edit session
- Adds conditionally shown warning text and variable submit button text to ownership type form template
- Updates ownership type step in property registration and update journey to match their designs
- Stops hiding ownership type change link on property record
N/A
=> PRSD-1107: Property No Session Update - Ownership Type

src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/LandlordViewModelTests.kt
PRSD-1100
Refactors TODOs in `LandlordViewModelTests` to not rely on multiple tickets
- Makes each TODO in `LandlordViewModelTests` rely on one ticket, rather than a set of them
N/A
=> PRSD-1100: Refactors TODOs in LandlordViewModelTests

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/LandlordViewModel.kt, src/main/resources/templates/forms/emailForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordDetailsUpdateJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/LandlordViewModelTests.kt
PRSD-1103
Implements updating landlord email without an edit session
- Adds conditionally shown warning text to email form template
- Updates email step in landlord update journey to match design
- Stops hiding email change link on landlord record
N/A
=> PRSD-1103: Landlord No Session Update - Email

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/LandlordViewModel.kt, src/main/resources/templates/forms/dateForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordDetailsUpdateJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/LandlordViewModelTests.kt
PRSD-1102
Implements updating landlord DOB without an edit session
- Adds conditionally shown warning text to DOB form template
- Updates DOB step in landlord update journey to match design
- Stops hiding name change link on landlord record
N/A
=> PRSD-1102: Landlord No Session Update - DOB

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/LandlordRegistrationJourneyFactory.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/api/controllers/JourneyDataController.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/api/requestModels/SetJourneyDataRequestModel.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
PRSD-623
Creates controller for setting journey data in tests
- Creates controller (in test module) with endpoint for setting journey data
- Refactors a single page journey test to use created endpoint as PoC
- The next PR for this ticket will refactor be an integration test refactor that makes use of the journey data setting endpoint
=> PRSD-623: Create Journey Data Controller

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/GroupedUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/UpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/PropertyDetailsUpdateJourneyFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/LandlordDetailsUpdateStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/StepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/UpdatePropertyDetailsStepId.kt
PRSD-1108
Modifies update journeys to support new CYA flow.
- Creates new step ID interface for update journeys
- Modifies update journeys to support new CYA flow
- Changes update journey `unreachableStepRedirect`s to their corresponding details pages
This PR covers functionality common to all update journeys. The next PR for this ticket will focus on using the new CYA flow when updating property licensing.
=> PRSD-1108: Use new CYA Flow in Update Journey

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyDetailsController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/GroupedUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/Journey.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/StepRouter.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/PropertyDetailsUpdateJourneyFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/LandlordDetailsUpdateStepId.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyDetailsControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/GroupedUpdateJourneyTests.kt
PRSD-1108
Fixes grouped update journey CYA links
- Makes `LandlordDetailsUpdateJourney` a non-grouped update journey as it currently doesn't have grouped updates
- Prevents property update journey back URLs from being overridden when changing answers
- Creates grouped update step router so CYA steps are seen as separate from the other steps in their groups
N/A
=> PRSD-1108: Fix Grouped Update Journey CYA Links

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt
PRSD-734
Update back links on the first page of journeys where it is not set.
* Updated the back url for the first page of registering a property to go to the landlord dashboard.
* Updated the back url for the first page of registering as a landlord to go to the journey intro page.
I've left the first page of the register as an LA user without a back link as you have reached it from an email so it's not very useful.
I've currently not added any tests for these back links. Do you think I need to add them?
=> PRSD-734: Change initial journey step back links

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourneyTests.kt
PRSD-NONE
Use filtered or session journey data where appropriate in the property compliance journey
- Modifies property compliance journey to use filtered or session journey data where appropriate
N/A
=> PRSD-NONE: Clean up (Filtered) Journey Data usage in Property Compliance Journey

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/DeregisterLandlordController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/LandlordDeregistrationJourneyFactory.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/DeregisterLandlordControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDeregistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordDeregistrationJourneyPages/AreYouSureFormPageLandlordDeregistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordDeregistrationJourneyPages/ConfirmationPageLandlordDeregistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordDeregistrationJourneyPages/ReasonFormPageLandlordDeregistration.kt
PRSD-458
Start every landlord endpoint with `/landlord`. In this PR: DeregisterLandlordController endpoints
Add /landlord to the start of the endpoints in DeregisterLandlordController 
This does not complete the ticket (it might be one PR per controller as they could get long otherwise)
=> PRSD-458: Precede DeregisterLandlordController endpoints with /landlord

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/DeregisterPropertyController.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/DeregisterPropertyControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyDeregistrationJourneyPages/AreYouSureFormPagePropertyDeregistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyDeregistrationJourneyPages/ConfirmationPagePropertyDeregistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyDeregistrationJourneyPages/ReasonPagePropertyDeregistration.kt
PRSD-458
Start every landlord endpoint with `/landlord`. In this PR: DeregisterPropertyController endpoints
Add /landlord to the start of the endpoints in DeregisterPropertyController
This does not complete the ticket (it might be one PR per controller as they could get long otherwise)
=> PRSD-458: Precede DeregisterPropertyController endpoints with /landlord

src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/IntegrationTest.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordRegistrationSinglePageTests.kt
PRSD-NONE
Orders integration tests so ones with different seed data run last
- Gives integration tests a custom orderer that makes nested tests with seed data run last
- Removes custom `LandlordRegistrationSinglePageTests` as no longer needed
N/A
=> PRSD-NONE: Order Integration Tests

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/PropertyComplianceConfirmationMessageKeys.kt, src/main/resources/templates/fullyCompliantPropertyConfirmation.html, src/main/resources/templates/partiallyCompliantPropertyConfirmation.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/PropertyComplianceConfirmationMessageKeysTests.kt
PRSD-965
Renames property compliance confirmation message model for clarity
- Clarifies that property compliance confirmation message model "messages" are "message keys"
N/A
=> PRSD-965: Renames Property Compliance Confirmation Message Model

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/templates/forms/eicrExemptionConfirmationForm.html, src/main/resources/templates/forms/eicrExemptionMissingForm.html, src/main/resources/templates/forms/eicrOutdatedForm.html, src/main/resources/templates/forms/epcExemptionConfirmationForm.html, src/main/resources/templates/forms/epcExpiredForm.html, src/main/resources/templates/forms/epcExpiredLowRatingForm.html, src/main/resources/templates/forms/epcMissingForm.html, src/main/resources/templates/forms/gasSafetyExemptionConfirmationForm.html, src/main/resources/templates/forms/gasSafetyExemptionMissingForm.html, src/main/resources/templates/forms/gasSafetyOutdatedForm.html, src/main/resources/templates/forms/lowEnergyRatingForm.html, src/main/resources/templates/forms/meesExemptionConfirmationForm.html
PRSD-962
Use generic submit buttons when changing property compliance journey answers
- Passes submit button text as a parameter into compliance journey templates
- Sets submit button text depending on whether the user is changing their answers
N/A
- When not changing your answers:
- When changing your answers:
=> PRSD-962: Use generic submit button when changing answers

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/UrlParameterNames.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyDetailsController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLandlordController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/GroupedUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/Journey.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/StepRouter.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/PropertyComplianceJourneyFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/PropertyDetailsUpdateJourneyFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyComplianceCheckAnswersPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/LookupAddressStep.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/Step.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/factories/PropertyDetailsUpdateJourneyStepFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/GroupedJourneyExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/SummaryListRowViewModel.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyDetailsControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/GroupedJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/GroupedUpdateJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/JourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPageTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyComplianceCheckAnswersPageTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPageTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/urlProviders/LandlordDashboardUrlTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/urlProviders/PropertyComplianceInfoUrlTests.kt
PRSD-962
Show 'View' link instead of 'Change' for landlord responsibility declarations
- Updates references to 'changing answers' to 'checking answers' instead
- Shows 'View' link instead of 'Change' for landlord responsibility declarations
N/A
=> PRSD-962: View Landlord Responsibilities when CYA

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/LocalAuthorityDashboardController.kt, src/main/resources/messages.properties, src/main/resources/templates/localAuthorityDashboard.html
PRSD-1357
Remove the ‘About the pilot’ link and description from the local authority dashboard
Per this [comment](https://mhclgdigital.atlassian.net/browse/PRSD-1357?focusedCommentId=711343) in QA remove the incorrect content from the LA dashboard
=> PRSD-1357: removed incorrect content

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/AlphabetConstants.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersController.kt, src/main/resources/messages.properties, src/main/resources/templates/inviteLAUser.html
PRSD-1357
Fix content on the invite LA user page
Update heading text
Add the line "They must have a/an {localCouncilName} email address to get an invite."
=> PRSD-1357: fix content invite la user page

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/CheckAnswersPage.kt
PRSD-NONE
CYA pages logic should only depend on the 'active route' through the journey.
Without the change on a CYA page for a journey that has been filled in multiple times down multiple routes (e.g. upload a gas safety cert then change to list an exemption then change to say no exemption) the logic of what the show and where to link can be influenced by data that's not currently 'active' (same e.g. the presence of an issue date). This ensures that the only data available to a CYA page is both submittable AND active.
=> PRSD-NONE: Fix CYA pages using off journey logic

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/factories/PropertyDetailsUpdateJourneyStepFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/JourneyExtensions.kt
PRSD-NONE
Use default backlinks for all journeys with a task list.
- Removes (non-first step) backlink overriding from journeys with a task list.
This may be a temporary measure; PRSD-1420 will determine our standard for journeys with a task list.
=> PRSD-NONE: Standardise JourneyWithTaskList Backlinks

src/main/resources/messages.properties, src/main/resources/templates/registerLAUserSuccess.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/laUserRegistrationJourneyPages/ConfirmationPageLaUserRegistration.kt
PRSD-1357
Content and style changes for LA screens
Update the heading 2 size on the confirmation screen - and update tests
Remove some text from the invite LA user screen
=> PRSD-1357: content update la screens

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityInvitationService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LaUserRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LaUserRegistrationSinglePageTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/ErrorPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/ErrorBasePage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/laUserRegistrationJourneyPages/InvalidLinkPageLaUserRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/LocalAuthorityInvitationServiceTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/urlProviders/InvitationUrlTests.kt, src/test/resources/data-mockuser-with-expired-invitation.sql
PRSD-1410
Make sure user can reach Invalid Link error page when using an Invalid Token
I changed the logic in the controller to check for a valid token (without checking for expiry) first and then to have the expiry check happen separately.
Added to tests to catch this bug if it reoccurs.
=> PRSD-1410: invalid token page

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/Journey.kt
PRSD-NONE
Only saves filtered journey data to the DB
- Uses filtered journey data (instead of full journey data) when saving to the DB
- This PR enables us to determine the paths of incomplete journeys, which we will need to know for PRSD-1394
=> PRSD-NONE: Only saves filtered journey data to the DB

src/main/kotlin/uk/gov/communities/prsdb/webapp/services/AwsS3FileDownloader.kt, src/main/resources/application.yml, src/test/resources/application.yml
PRSD-976
Make the duration of the signed urls for document download configurable. I'm defaulting it to 1 hour.
=> PRSD-976: Make the signature duration configurable

src/main/resources/messages.properties, src/main/resources/templates/deleteLAUser.html
PRSD-1357
Stop using warning styled text on delete LC user page
As above
=> PRSD-1357: fix styling on delete LC user page

src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/LandlordPrivacyNoticePage.kt
PRSD-676
Fix the ico website link text on the landlord privacy notice
From `www.ico.org.uk/` to `https://ico.org.uk/`
=> PRSD-676: content fix privacy notice page ico link text

src/main/resources/templates/fragments/forms/fixedWidthTextInput.html, src/main/resources/templates/passcodeEntry.html
PRSD-1423
Sets passcode entry form's field width
As above
N/A
##Screenshots
=> PRSD-1423: Sets passcode entry form's field width

src/main/resources/messages.properties
PRSD-1516
Resolve minor copy tweaks suggested in QA
* Turned `'`s into `\u2018`s
* Added a missing space
(These were both pre-existing issues, not introduced in PRSD-1516, but we'll fix while we're here)
N/A
=> PRSD-1516: QA fixes: 's to \u2019s; add missing space

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/factories/PropertyComplianceSharedStepFactory.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/uploadCertificateForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/SummaryList.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/UploadCertificateFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/CheckAndSubmitPagePropertyCompliance.kt
PRSD-1418
Updates certificate upload page to match new designs
- Updates certificate form's content to match new designs
- Adds logic for conditionally showing content to users who've already uploaded a certificate
- This PR doesn't complete the ticket
- First visit to cert upload page
- Subsequent visits to cert upload page (if file uploaded)
=> PRSD-1418: Revisit cert. upload page without re-uploading

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt
PRSD-1528
Fix saveAfterSubmit error on some landlord registration steps
Added `saveAfterSubmit = false` to `noAddressFoundStep` and `noContactAddressFoundStep`
N/A
=> PRSD-1528: Fix saveAfterSubmit error on some landlord registration steps

src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/propertyComplianceViewModels/GasSafetyViewModelFactory.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/propertyComplianceViewModels/GasSafetyViewModelBuilderTests.kt
PRSD-1553
Remove gas safety engineer row from property record when empty
As above and updated test
=> PRSD-1553: Remove gas safety engineer row from property record when empty

.run/local.run.xml, src/main/kotlin/uk/gov/communities/prsdb/webapp/config/OSPlacesConfig.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/local/api/controllers/OSPlacesAPIStubController.kt, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/resources/application.yml
PRSD-1021
Renames OS API key to be more general
- Renames OS API key and mock profile to be more general
- Updates dev `.env` file in Keeper
- This ticket prompted the renaming as we'll be using another OS API (with the same key)
- This PR shouldn't be merged until the [corresponding infra one](https://github.com/communitiesuk/prsdb-infra/pull/182) is
=> PRSD-1021: Renames OS API key

.github/workflows/build-and-deploy.yml, .github/workflows/build-and-test.yml, ReadMe.md
PRSD-934
Add ktLintFormat to pre-commit hook instructions  and pipelines
As above
When this is merged it I will also send a message in dev slack asking everyone to add the ktLintFormat to their pre-commit hooks
N/A
=> PRSD-934: Add ktLintFormat to pre-commit hook instructions and pipelines
