communitiesuk/prsdb-webapp

src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/AuditableEntity.kt
- Annotates `AuditableEntity.lastModifiedDate` with `@LastModifiedDate` instead of `@CreatedDate`
=> PRSD-297: Fix AuditableEntity.lastModifiedDate annotation

src/main/kotlin/uk/gov/communities/prsdb/webapp/config/CustomSecurityConfig.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/IntegrationTest.kt
Changes integration test profile to use kebab case
=> PRSD-NONE: Changes integration test profile to use kebab case

src/main/resources/data-local.sql
Fixes data-local.sql, some extra semi-colons had sneaked in, probably in a merge conflict!
=> PRSD-NONE: fix data-local.sql

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LaUserRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/Page.kt
Changes Page's contentKeys attribute to content so objects can be added the the model
=> PRSD-422: Changes Page's contentKeys attribute to content 

src/main/resources/messages.properties
A one letter PR to fix a typo on the number of households page...
=> PRSD-494: Fix typo

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/LandlordRegistrationStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/formModels/DeclarationFormModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/CheckboxViewModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/validation/TrueConstraintValidator.kt, src/main/resources/application.yml, src/main/resources/messages.properties, src/main/resources/templates/forms/declarationForm.html, src/main/resources/templates/fragments/forms/checkboxes.html, src/main/resources/templates/fragments/forms/inputGroup.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/Checkboxes.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/Form.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/Radios.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/ConfirmationPageLandlordRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/DeclarationFormPageLandlordRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/SummaryPageLandlordRegistration.kt
- Creates checkboxes component
- Adds `Declaration` step to `LandlordRegistrationJourney`
- Integration tests for the `Declaration` step
Declaration page
Declaration page with error message
=> PRSD-373: Landlord Registration Declaration

src/main/resources/messages.properties, src/main/resources/templates/forms/selectLocalAuthorityForm.html
Adding the two URLs Sam's highlighted to the pages on which they belong.
=> Prsd none add urls to links

adrs/0019-search-algorithm-basis.md, adrs/0020-exact-trigram-search.md
Proposed ADR for choosing trigram search as the basis of searching through e.g. names, emails, phone numbers etc.
=> PRSD-496: Search basis adr draft

src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/LandlordJourneyDataHelper.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/JourneyDataService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/LandlordJourneyDataHelperTests.kt
- Adds more field type retrieval methods to `JourneyDataService`
- Creates `LandlordJourneyDataHelper` for retrieving specific fields from the journey data
=> PRSD-642: Landlord Journey Data Helper

src/main/resources/emails/ExampleEmail.md
- Matches ExampleEmail.md to the corresponding template in Notify
- Matches the "LA User Invitation" email in Notify to the corresponding one in the codebase
=> PRSD-NONE: Matches Source Controlled Email Templates to their Notify Counterparts

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LaUserRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/ConfirmIdentityPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LaUserRegistrationCheckAnswersPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/FormSummaryDataModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/FormSummaryViewModel.kt, src/main/resources/templates/forms/checkAnswersForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LaUserRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/Form.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/SummaryList.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/laUserRegistrationJourneyPages/CheckAnswersPageLaUserRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/CheckAnswersPageLandlordRegistration.kt
- Renames SummaryPages to CheckAnswers pages
- Converts checkAnswersForm.html into a question page
- Changes FormSummaryDataModel to a view model
- Creates SummaryList page component
- Refactors CheckAnswersPages to be a FormBasePage
=> PRSD-372: Refactor Summary Pages

.github/workflows/build-and-deploy.yml
Dependent on https://github.com/communitiesuk/prsdb-infra/pull/23 being merged
=> PRSD-752: Makes pipeline create task definition

src/main/resources/templates/fragments/searchBar.html, src/main/resources/templates/searchLandlord.html
=> PRSD-649: Fixes landlord search page spacing issues

rollup.config.mjs, src/main/js/index.js, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/resources/templates/fragments/layout.html, src/main/resources/templates/searchLandlord.html
- Bundles JS for MoJ design system
- Adds back link to landlord search page
=> PRSD-649: Landlord Search Back Link

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/URIQueryBuilder.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/PaginationViewModel.kt, src/main/resources/templates/fragments/pagination/listAllPages.html, src/main/resources/templates/fragments/pagination/listHighlightedPages.html, src/main/resources/templates/fragments/pagination/next.html, src/main/resources/templates/fragments/pagination/pageLink.html, src/main/resources/templates/fragments/pagination/pagination.html, src/main/resources/templates/fragments/pagination/previous.html, src/main/resources/templates/manageLAUsers.html, src/main/resources/templates/searchLandlord.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/URIQueryBuilderTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/PaginationViewModelTests.kt
- Creates and tests `URIQueryBuilder`
- Creates and tests `PaginationViewModel`
- Refactors to use `PaginationViewModel` on manage LA and search landlord pages
- Updates `page` query parameter to have a minimum value (1)
- Updates affected controller tests
=> PRSD-NONE: Pagination Model Refactor

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/main/resources/messages.properties, src/main/resources/templates/searchProperty.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/SearchRegisterTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/SearchPropertyRegisterPage.kt
Feature: Updates search property page to show error when no results are found
Test: Updates search property integration tests
Screenshot:
=> PRSD-662: Property Search - No Results

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterController.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/SearchRegisterTests.kt
Links property search results to LA view of property record (instead of landlord view)
=> PRSD-659: Links property search results to LA view of property record

src/main/resources/messages.properties
- Updates filter content to match design
=> PRSD-651: Fixes filter content

src/main/kotlin/uk/gov/communities/prsdb/webapp/services/UserRolesService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/UserRolesServiceTests.kt
Changed `UserRolesService` to use `LandlordRepository` instead of `LandlordUserReopsitory`
Update affected tests
=> feat/PRSD 765 use landlord instead of landlordUser in userRolesService

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/tasks/TaskList.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyRegistrationJourneyTests.kt
(a) Fixes the bug that came up in internal demo earlier today
(b) Fixes the rather egregious fact that both my integration tests that should have caught that issue were non functional (such that they always passed)
=> PRSD-600: Fix incorrect task completion logic and tests

.github/workflows/build-and-deploy.yml
=> PRSD-NONE: Corrects slack reference error

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/Step.kt
This was annoying me while I was debugging with steps.
=> PRSD-NONE: Add useful to string on step

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyDetailsController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extenstions/SummaryListViewModelExtensionHelper.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsLandlordViewModel.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/summaryModels/PropertyDetailsLandlordViewModelTests.kt
=> PRSD-724: Removes Change Links from Property Details - Landlord Tab

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/LandlordDetailsController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLandlordController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterPropertyController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/Journey.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/UpdateJourney.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/JourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/LandlordRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/PropertyRegistrationJourneyTests.kt
- Passes step path segments instead of IDs into journey methods
- Updates affected tests
=> PRSD-NONE: Passes Step Path Segments into Journey Methods

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDeregistrationJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PageWithContentProvider.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PageWithContentProviders.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PageWithContentProviderTests.kt
Replaces `PageWithSingleLineAddress` with `PageWithContentProviders`, which can be used more generally.
=> PRSD-NONE: Creates PageWithContentProviders

adrs/0026-address-lookups-revisited.md
=> PRSD-929: Fix typo in ADR-0026

adrs/0026-non-deterministic-journey-support.md, adrs/0027-non-deterministic-journey-support.md
Creates an ADR for choosing not to support non-deterministic journeys
=> PRSD-946: Creates ADR for Non-deterministic Journey Support

adrs/0028-database-migrations.md
Hopefully an uncontroversial one. I'll admit to having not checked the number is correct vs the other in-flight ADRs, but will resolve that before merging
=> PRSD-767: Adds proposed ADR for migrations

adrs/0026-address-lookups-revisited.md
I stupidly forgot to update this before merging...
=> PRSD-929 Update ADR-26 to Accepted status

.github/workflows/reset-database-integration.yml, .github/workflows/reset-database-test.yml, .github/workflows/reset-database.yml
- Makes `reset-database.yml` a reusable workflow
- Parameterizes `reset-database.yml` on target environment
- Creates `reset-database-integration.yml` and `reset-database-test.yml` workflows, which call `reset-database.yml`
=> PRSD-1020: Github Actions for manually resetting lower environment DBs

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/factories/PropertyComplianceJourneyFactory.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/PropertyComplianceStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyDataExtensions/PropertyComplianceJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/GasSafetyFormModel.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/gasSafetyForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyDataExtensions/PropertyComplianceJourneyDataExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/TaskListPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
- Adds `loadJourneyDataIfNotLoaded()` call to `PropertyComplianceJourney`'s constructor
- Creates gas safety form model and template
- Creates `PropertyComplianceJourneyDataExtensions.getHasGasSafetyCert()`
- Adds gas safety step and task to `PropertyComplianceJourney`
- Creates `PropertyComplianceController` POST journey step endpoint
- Unit tests `PropertyComplianceJourneyDataExtensions.getHasGasSafetyCert()`
- Tests `PropertyComplianceController` POST journey step endpoint
- Integration tests gas safety step of `PropertyComplianceJourney`
- Gas Safety Page
- Error screen
=> PRSD-942: Compliance Journey - Gas Safety

src/main/resources/emails/LandlordRegistrationConfirmation.md, src/main/resources/emails/LandlordWithPropertiesDeregistrationConfirmation.md, src/main/resources/emails/PropertyDeregistrationConfirmation.md, src/main/resources/emails/PropertyRegistrationConfirmation.md
Adds missing full stops to email templates...
Note the tests will fail until I update the notify templates, I'm hoping to do this just before merging to minimise the time when everyone else's tests will fail!
=> PRSD-NONE: Add missing full stops to email templates

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/PropertyComplianceStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/DateTimeHelper.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/JourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/TodayOrPastDateFormModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/validation/DateValidator.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyDataExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/UpdateLandlordDetailsJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/DateFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/DateOfBirthFormPageLandlordRegistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyIssueDatePagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/updateLandlordDetailsPages/DateOfBirthFormPageUpdateLandlordDetails.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/validation/DateValidatorTests.kt
- Adds Gas Safety Certificate Issue Date step to Property Compliance Journey
- Creates form model for non-future dates
- Updates year validation method to match its error message
- Creates journey data extension methods for 
- Retrieving a date
- Checking if a gas safety cert. is out of date (a year or more old)
- Unit tests the new journey data extension methods
- Adds integration tests for the Gas Safety Certificate Issue Date step
- Gas Safety Certificate Issue Date step page
- Future date error
=> PRSD-943: Property Compliance - Gas Safety Cert. Issue Date

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/PropertyComplianceStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyDataExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/GasSafetyExemptionFormModel.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/exemptionForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyDataExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyExemptionPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
PRSD-949
Adds Gas Safety Exemption step to Property Compliance Journey
- Creates form model and template for gas safety exemption input
- Creates journey data extension for determining gas safety exemption status
- Adds Gas Safe Engineer Number step to Property Compliance Journey
N/A
=> PRSD-949: Property Compliance - Gas Safety Exemption

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/TextAreaConstants.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/GasSafetyExemptionOtherReasonFormModel.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/exemptionOtherReasonForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/ReasonFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordDeregistrationJourneyPages/ReasonFormPageLandlordDeregistration.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyExemptionOtherReasonPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyDeregistrationJourneyPages/ReasonPagePropertyDeregistration.kt
PRSD-994
Adds Gas Safety Exemption Other Reason step to Property Compliance Journey
- Creates form model and template for gas safety exemption input
- Adds Gas Safety Exemption Other Reason step to Property Compliance Journey
N/A
=> PRSD-994: Property Compliance - Gas Safety Exemption Other Reason

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/gasSafetyExemptionConfirmationForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyExemptionConfirmationPagePropertyCompliance.kt
PRSD-951
Adds Gas Safety Exemption Confirmation step to Property Compliance Journey
- Creates template for gas safety exemption confirmation page
- Adds Gas Safety Exemption Confirmation step to Property Compliance Journey
N/A
=> PRSD-951: Property Compliance - Gas Safety Exemption Confirmation

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/gasSafetyExemptionMissingForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyExemptionMissingPagePropertyCompliance.kt
PRSD-952
Adds Gas Safety Exemption Missing step to Property Compliance Journey
- Creates template for gas safety exemption missing page
- Adds Gas Safety Exemption Missing step to Property Compliance Journey
N/A
=> PRSD-952: Property Compliance - Gas Safety Exemption Missing

src/main/resources/messages.properties
PRSD-994
Fixes typo in fieldset heading
- Fixes typo in fieldset heading message key
N/A
=> PRSD-994: Fixes typo in fieldset heading

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/PropertyComplianceStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/EicrFormModel.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/CertificateFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
PRSD-954
Adds EICR step to property compliance journey
- Creates form model for EICR step
- Creates journey data extension for determining EICR status
- Adds EICR step to property compliance journey
N/A
=> PRSD-954: Property Compliance - EICR

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/PropertyComplianceStepId.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyExtensions.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/requestModels/formModels/EicrExemptionFormModel.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/extensions/journeyExtensions/PropertyComplianceJourneyExtensionsTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/basePages/ExemptionFormPage.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrExemptionPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/GasSafetyExemptionPagePropertyCompliance.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/testHelpers/builders/JourneyDataBuilder.kt
PRSD-957
Adds EICR exemption step to property compliance journey
- Creates form model for EICR exemption step
- Creates extension method for determining if user has an EICR exemption
- Adds EICR exemption step to property compliance journey
N/A
=> PRSD-957: Property Compliance - EICR Exemption

src/main/resources/messages.properties
PRSD-1098
Updates content to match design
- Updates the upload certificate confirmation form's content to match the design
N/A
=> PRSD-1098: Updates content to match design

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/eicrExemptionConfirmationForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrExemptionConfirmationPagePropertyCompliance.kt
PRSD-959
Adds EICR exemption confirmation step to property compliance journey
- Creates template for EICR exemption confirmation page
- Adds EICR exemption confirmation step to property compliance journey
N/A
=> PRSD-959: Property Compliance - EICR Exemption Confirmation

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrUploadConfirmationPagePropertyCompliance.kt
PRSD-1128
Adds EICR upload confirmation step to property compliance journey
- Adds EICR upload confirmation step to property compliance journey
N/A
=> PRSD-1128: Compliance Journey - EICR Upload Confirmation

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/ExternalLinks.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/eicrOutdatedForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrOutdatedPagePropertyCompliance.kt
PRSD-961
Adds EICR outdated step to property compliance journey
- Creates template for EICR outdated page
- Adds EICR outdated step to property compliance journey
N/A
=> PRSD-961: Property Compliance - EICR Outdated

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/ExternalLinks.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyComplianceJourney.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/eicrExemptionMissingForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyComplianceJourneyPages/EicrExemptionMissingPagePropertyCompliance.kt
PRSD-960
Adds EICR exemption missing step to property compliance journey
- Creates template for EICR exemption missing page
- Adds EICR exemption missing step to property compliance journey
N/A
=> PRSD-960: Property Compliance - EICR Exemption Missing

src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyComplianceJourneyTests.kt
PRSD-NONE
Cleans up property compliance journey tests
- Addresses hanging TODOs
- Removes unnecessary `page` parameters
N/A
=> PRSD-NONE: Cleans Up Property Compliance Journey Tests

src/main/kotlin/uk/gov/communities/prsdb/webapp/config/OneLoginConfig.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ControllerTest.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/LocalAuthorityDashboardControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/ManageLocalAuthorityUsersControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyDetailsControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/RegisterLAUserControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/SearchRegisterControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDeregistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordDeregistrationAreYouSurePageTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/IntegrationTest.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LaUserRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/urlProviders/InvitationUrlTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/urlProviders/LandlordDashboardUrlTests.kt
PRSD-NONE
Cleans up deprecations caused by upgrading Springboot
- Replaces deprecated classes 
- Makes any necessary changes caused by changed dependencies
N/A
=> PRSD-NONE: Clean Up Deprecations

src/main/kotlin/uk/gov/communities/prsdb/webapp/clients/EpcRegisterClient.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/examples/ExampleEpcController.kt
PRSD-1065
Ensure we can search for UPRNs over 10 digits.
=> PRSD-1065: Switch to long UPRNs

src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/LandlordDetailsControllerTests.kt
PRSD-NONE
Adds tests for landlord details controller
- Adds tests for landlord details controller
N/A
=> PRSD-NONE: Landlord Details Controller Tests

.run/local.run.xml, src/main/resources/data-test.sql
PRSD-NONE
Fix seed data for `test` and re-adds docker job to local run config
Although this should technically be a hotfix on `test` since we just merged to test we can go main -> test to keep the git history clean
=> PRSD-NONE: Fixes test seed data and local run config

adrs/0000-adr-template.md, adrs/0015-end-to-end-test-framework.md, adrs/0016-database-migrations.md, adrs/0018-infrastructure-repository.md, adrs/0019-search-algorithm-basis.md, adrs/0021-vpc-configuration.md, adrs/0022-disaster-recovery.md, adrs/0023-ecr-hosting.md, adrs/0024-ecs-deployment.md, adrs/0025-file-uploads.md, adrs/0026-address-lookups-revisited.md, adrs/0027-non-deterministic-journey-support.md, adrs/0028-database-migrations.md, adrs/0029-scheduled-tasks.md
A handful of old ADRs were still in draft / proposed states, but in practice they've been accepted. This fixes that.
- Mark several ADRs as Accepted, with an approximate date
- Settle on a yyyy-MM-dd format for dates
- Consistently use LF line endings
ADR-0020, related to our triagram search solution, is still in draft. It's pending further investigation and testing with data, so I've left that as is.
=> PRSD-None: Tidy up old ADRs

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyDetailsUpdateJourney.kt
PRSD-NONE
Removes comments invalidated by code changes
- Removes update journey comments invalidated by removal of update session
N/A
=> PRSD-NONE: Removes invalid comments

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/LandlordDetailsController.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt
PRSD-NONE
Addresses TODOs for completed tickets
- Addresses TODOs for completed tickets
N/A
=> PRSD-NONE: Addresses TODOs for completed tickets

src/main/kotlin/uk/gov/communities/prsdb/webapp/examples/ExampleEmailSendingApplicationRunner.kt
PRSD-1282
Trivial change so that I can receive the emails sent by the example email sender to test my infrastructure changes.
=> PRSD-1282: Create initial real example email to prove event received

src/main/resources/templates/partiallyCompliantPropertyConfirmation.html
PRSD-964
Fixes incorrect link on partially compliant property confirmation page
- Fixes spelling error in link reference
N/A
=> PRSD-964: Fixes incorrect link

src/main/resources/data-test.sql
PRSD-NONE
Updates Sam's OneLogin ID in seed data
- Updates seed data for test environment to use Sam's communities account's OneLogin ID 
This PR has been raised as Sam wants to log into the test environment using his communities email from now on.
=> PRSD-NONE: Updates Sam's OneLogin ID in seed data

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceController.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/updateModels/PropertyComplianceUpdateModel.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyComplianceService.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/PropertyComplianceControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyComplianceServiceTests.kt
PRSD-1244
Creates service method for updating compliance records
- Creates model and service method for compliance record updates
N/A
=> PRSD-1244: Update Compliance Record

adrs/0032-web-analytics.md
PRSD-1268
An ADR to decide what web analytics setup we'll use
GA4 vs Plausible vs CloudFront logs
N/A
=> PRSD-1268 ADR for web analytics

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/CheckUpdateEicrAnswersPage.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/CheckUpdateGasSafetyAnswersPage.kt, src/main/resources/messages.properties
PRSD-1245
Fixes incorrect content on the compliance CYA pages.
See if you can guess which CYA page I copy and pasted to create the compliance update CYA pages.
=> PRSD-1245: Fix CYA summary text

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/factories/PropertyComplianceSharedStepFactory.kt
PRSD-1245
Do not ever try to save the update compliance journey.
=> PRSD-1245: Never attempt to save update journeys

.github/copilot-instructions.md
Removes accidentally committed copilot instructions
=> PRSD-NONE: Deletes copilot instrcutions from repo

src/main/resources/templates/fragments/layout.html
PRSD-1183
Add Plausible code snippet so that Plausible can track analytics
Add Plausible code snippet so that Plausible can track analytics.
Added to "layout.html" so that it is used on every page.
=> PRSD-1183: Add plausible analytics

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/GeneratePasscodeController.kt, src/main/resources/messages.properties, src/main/resources/templates/generatePasscode.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/GeneratePasscodeControllerTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/GeneratePasscodeTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/Navigator.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/ConfirmationBanner.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/GeneratePasscodePage.kt
PRSD-1423
Updates generate passcode page to match new designs
- Updates generate passcode page controller and template
- This PR doesn't complete the ticket
=> PRSD-1423: Updates generate passcode page

src/main/resources/messages.properties, src/main/resources/templates/fragments/forms/basicTextInput.html, src/main/resources/templates/fragments/forms/inputGroup.html, src/main/resources/templates/passcodeEntry.html
PRSD-1423
Updates passcode entry page to match new designs
- Updates passcode entry page template
- This PR doesn't complete the ticket
- Passcode entry page
- Validation error
=> PRSD-1423: Updates passcode entry page

src/main/kotlin/uk/gov/communities/prsdb/webapp/controllers/LocalAuthorityDashboardController.kt, src/main/resources/messages.properties, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/GeneratePasscodeTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LocalAuthorityDashboardTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/LocalAuthorityDashboardPage.kt
PRSD-1423
Updates generate passcode navigation link to match new designs
- Updates generate passcode navigation link's placement and wording
- This PR doesn't complete the ticket
=> PRSD-1423: Updates generate passcode nav link

.github/pull_request_template.md
PRSD-NONE
I almost missed some TODOs on my last ticket and thought this might be useful to add to the checklist.
=> PRSD-NONE: Add todo check to checklist

src/main/resources/messages.properties
PRSD-1380
Update header country of residence page
As above
=> PRSD-1380: Update header country of residence page

src/main/resources/emails/PropertyDeregistrationConfirmation.md, src/main/resources/emails/emailTemplates.json
PRSD-1393
Update property deregistration email template
As above
I have added a ticket for removing the old temp-late in 2 sprints time
=> PRSD-1393: Update property deregistration email template

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordDetailsUpdateJourney.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt, src/main/resources/messages.properties
PRSD-NONE
Resolve a merge conflict in the message.properties file
I've updated the landlord address update journey to use the generic landlord hint - this will need to be changed in PRDS-1380, but I wanted to remove the generic message key and keep this PR minimal.
=> PRSD-NONE: Fix merge conflict

src/main/resources/messages.properties
PRSD-1362
minor changes to content for landlord start page as requested.
=> PRSD-1362: changes requested as per comments

src/main/resources/emails/GiveFeedbackLater.md, src/main/resources/emails/emailTemplates.json
PRSD-1302
Updates feedback later email to use correct email.
=> PRSD-1302: Update email template

src/main/resources/messages.properties, src/main/resources/templates/registerPropertyConfirmation.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/PropertyRegistrationJourneyTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/propertyRegistrationJourneyPages/ConfirmationPagePropertyRegistration.kt
PRSD-1381
Fix most problems raised in QA
=> PRSD-1381: Small property registration content changes

src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyComplianceCheckAnswersPage.kt, src/main/resources/messages.properties, src/main/resources/templates/forms/propertyComplianceCheckAnswersForm.html, src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyComplianceCheckAnswersPageTests.kt
PRSD-1418
Updates the CYA page of the property compliance journey
As above
This PR (along with the other open ones at time of writing) complete this ticket
=> PRSD-1418: Updates CYA page

src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/ExternalLinks.kt, src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/factories/PropertyComplianceSharedStepFactory.kt, src/main/resources/templates/forms/lowEnergyRatingForm.html
PRSD-1418
Fixes incorrect link on low rated EPC page
As above
N/A
=> PRSD-1418: Fixes incorrect link

src/main/kotlin/uk/gov/communities/prsdb/webapp/config/security/LandlordSecurityConfig.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/controllers/BetaFeedbackControllerTests.kt
PRSD-1511
Make feedback page for landlords public
As above
N/A
=> PRSD-1511: Make feedback page for landlords public

src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordDashboardTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordPrivacyNoticeTests.kt, src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LocalAuthorityDashboardTests.kt
PRSD-1532
Remove external webpage dependencies from tests
As above
N/A
=> PRSD-1532: Remove external webpage dependencies from tests

.github/workflows/build-and-deploy.yml
PRSD-1531
Add slack reporting for test and production builds
Removed the is branch "main" from the re porting on slack action
I have not tested this manually
N/A
=> PRSD-1531: Add slack reporting for test and production builds

.github/workflows/build-and-deploy-integration.yml, .github/workflows/build-and-deploy-production.yml, .github/workflows/build-and-deploy-test.yml, .github/workflows/build-and-deploy.yml, .github/workflows/reset-database.yml
PRSD-1537
Refactors GitHub workflows to make use of update ECS service workflow
As above
This PR should not be merged until the [corresponding infra PR](https://github.com/communitiesuk/prsdb-infra/pull/171) is
=> PRSD-1537: Uses update ECS service workflow

docs/NotifyEmailsReadMe.md
PRSD-1541
Added Notify email ReadMe
As above
N/A
N/A
=> PRSD-1541: Added Notify email ReadMe

src/main/resources/emails/LocalCouncilUserInvitationInformAdminEmail.md
PRSD-1343
Changed wording on email template
=> PRSD-1343: template change
